name: Build and Publish Finet

on:
    push:
        tags:
            - "v*.*.*" # Trigger workflow when a tag like v1.0.0 is pushed

jobs:
    lint-build-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install build dependencies
              run: |
                python -m pip install --upgrade pip
                pip install ruff build twine
                pip install -r requirements.txt

            - name: Lint with Ruff
              run: ruff check . --output-format=github

            - name: Build package
              if: startsWith(github.ref, 'refs/tags/v')
              run: python -m build

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha # Also tag with the commit SHA

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
